[[left]]
name = "dir"
color.background = "blue"
color.foreground = "black"

[[left]]
name = "git"
color.background = "green"
color.foreground = "black"

[[right]]
name = "status"
color.background = "white"
color.foreground = "black"

[[right]]
name = "cmdtime"
color.background = "magenta"
color.foreground = "black"

[[right]]
name = "shell"
color.background = "green"
color.foreground = "black"

[[left]]
name = "usercmd"
color.background = "green"
color.foreground = "black"
[usercmd]
command = "hostname"

[[left]]
name = "os"
color.background = "grey"
color.foreground = "black"