name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Check with rustfmt
        run: cargo fmt --verbose -- --check
      - name: Check with Clippy
        run: cargo clippy --verbose
      - name: Run tests
        run: cargo test --verbose
